services:
  app:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
      - redis
    volumes:
      - ./api:/var/www/html

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./base_query.sql:/docker-entrypoint-initdb.d/base_query.sql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  pgdata:
  redis_data: